# Generated by Django 2.2.2 on 2019-06-27 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='عنوان چارت')),
                ('is_active', models.BooleanField(verbose_name='فعال بودن')),
                ('degree', models.CharField(max_length=20, verbose_name='مقطع')),
                ('acceptance_date', models.DateField(verbose_name='تاریخ تصویب')),
            ],
            options={
                'verbose_name': 'چارت تحصیلی ',
                'verbose_name_plural': 'چارت\u200cهای تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان')),
                ('course_type', models.IntegerField(choices=[(1, 'درس اصلی'), (2, 'درس تخصصی'), (3, 'درس عمومی'), (4, 'درس اختیاری')], verbose_name='نوع درس')),
                ('vahed_nazari', models.IntegerField(verbose_name='تعداد واحد نظری')),
                ('vahed_amali', models.IntegerField(verbose_name='تعداد واحد عملی')),
                ('corequisite_courses', models.ManyToManyField(blank=True, related_name='_course_corequisite_courses_+', to='core.Course', verbose_name='هم\u200cنیاز')),
                ('prerequisite_courses', models.ManyToManyField(blank=True, related_name='_course_prerequisite_courses_+', to='core.Course', verbose_name='پیش\u200cنیاز')),
            ],
            options={
                'verbose_name': 'درس ',
                'verbose_name_plural': 'درس\u200cها ',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام دانشگاه')),
                ('has_associates_degree', models.NullBooleanField(verbose_name='مقطع کاردانی')),
                ('has_bachelors_degree', models.NullBooleanField(verbose_name='مقطع کارشناسی')),
                ('has_masters_degree', models.NullBooleanField(verbose_name='مقطع کارشناسی ارشد')),
                ('has_doctorate_degree', models.NullBooleanField(verbose_name='مقطع دکتری')),
            ],
            options={
                'verbose_name': ' دانشگاه',
                'verbose_name_plural': 'دانشگاه\u200cها ',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.IntegerField(choices=[(1, 'کاردانی'), (2, 'کارشناسی'), (3, 'کارشناسی ارشد'), (4, 'دکتری')], verbose_name='مقطع تحصیلی')),
                ('entrance_year', models.DateField(verbose_name='سال ورود')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Chart', verbose_name='چارت')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'مقطع تحصیلی ',
                'verbose_name_plural': 'مقاطع تحصیلی ',
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='نمره')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Course', verbose_name='درس')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Study', verbose_name='تحصیل')),
            ],
            options={
                'verbose_name': 'نمره ',
                'verbose_name_plural': 'نمره\u200cها ',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام دانشکده')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.University', verbose_name='نام دانشگاه')),
            ],
            options={
                'verbose_name': 'دانشکده ',
                'verbose_name_plural': 'دانشکده\u200cها ',
            },
        ),
        migrations.AddField(
            model_name='chart',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='core.Course'),
        ),
        migrations.AddField(
            model_name='chart',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Faculty', verbose_name='دانشکده'),
        ),
    ]
