# Generated by Django 2.2.3 on 2019-07-07 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='نمره')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Course', verbose_name='درس')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Study', verbose_name='تحصیل')),
            ],
            options={
                'verbose_name': 'نمره ',
                'verbose_name_plural': 'نمره\u200cها ',
            },
        ),
        migrations.DeleteModel(
            name='Scores',
        ),
    ]
