# Generated by Django 2.2.3 on 2019-07-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190707_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='study',
            name='entrance_year',
        ),
        migrations.AlterField(
            model_name='chart',
            name='degree',
            field=models.IntegerField(choices=[(1, 'کاردانی'), (2, 'کارشناسی'), (3, 'کارشناسی ارشد'), (4, 'دکتری')], verbose_name='مقطع تحصیلی'),
        ),
    ]
