# Generated by Django 2.2.2 on 2019-07-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190709_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='counted',
            field=models.BooleanField(default=False, verbose_name='محاسبه شود'),
        ),
    ]
