# Generated by Django 2.2.2 on 2019-07-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_score_counted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='counted',
            new_name='is_counted',
        ),
    ]
