# Generated by Django 2.2.2 on 2021-06-07 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190710_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='degree',
            field=models.IntegerField(choices=[(1, 'کاردانی'), (2, 'کارشناسی'), (3, 'کارشناسی ارشد'), (4, 'دکتری')], default=2, verbose_name='مقطع تحصیلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study',
            name='entrance_year',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='سال ورود'),
            preserve_default=False,
        ),
    ]
